### ISSUE TITLE
calculating important feature for each row

### ISSUE THREAD

**Issue by stray128** [nestordemeure/permutationImportance#1]
How do i calculate feature importance for each row of the data?

**Comment by nestordemeure** [comment]
This library requires aggregating information between rows (for its permutation phase). To look at the impact of individual features into giving a result for a given row I would use Shapley values and in particular look into the `decision_plot` and `waterfall_plot`.

You can see an example [here](https://github.com/nestordemeure/fastshap/blob/master/nbs/01_interpret.ipynb).
